name = "ketsuin-leaderboard-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[vars]
ALLOWED_ORIGINS = "http://localhost:5173,https://huanglizhuo.github.io,https://ketsuin.clothpath.com"

migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"
database_name = "ketsuin-leaderboard"
database_id = "c1dee303-3f80-495d-a6ae-79e3ccbfbf5e"
